language: go
go:
  - "1.11.x"
env:
  - GO111MODULE=on

install:
  - go install -v -mod=vendor ./...
  - GO111MODULE=off go get -v github.com/letsencrypt/pebble/cmd/pebble
  - GO111MODULE=off go install -v github.com/letsencrypt/pebble/cmd/pebble

before_script:
  # Start Pebble with the correct env & arguments for our tests
  - PEBBLE_WFE_NONCEREJECT=0 pebble -dnsserver 127.0.0.1:5252 &
  # Wait for Pebble to become available before proceeding
  - until </dev/tcp/localhost/14000 ; do sleep 0.1 ; done

script:
  - go test -v -mod=vendor ./...
  - go install -v -mod=vendor ./...
  - acmeshell -pebble < test/script.txt
