language: go
go:
  - "1.11.x"
env:
  - GO111MODULE=on

install:
  # Install `golangci-lint` using their installer script
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.13.2
  - go install -v -mod=vendor ./...
  - GO111MODULE=off go get -v github.com/letsencrypt/pebble/cmd/pebble
  - GO111MODULE=off go install -v github.com/letsencrypt/pebble/cmd/pebble

before_script:
  # Start Pebble with the correct env & arguments for our tests
  - PEBBLE_WFE_NONCEREJECT=0 pebble -strict -dnsserver 127.0.0.1:5252 &
  # Wait for Pebble to become available before proceeding
  - until </dev/tcp/localhost/14000 ; do sleep 0.1 ; done

script:
  # This `go mod download` is a hack...
  # Without it there seem to be occasional golangci-lint flakes of the form:
  #   ERRO Running error: context loading failed: failed to load program with go/packages: 
  #   go [list -e -json -compiled -test=true -export=false -deps=true -find=false -- ./...]: 
  #   exit status 1: go: golang.org/x/net@v0.0.0-20190213061140-3a22650c66bd: 
  #   git init --bare in ...
  # error: could not write config file ...: No such file or directory
  # go: error loading module requirements 
  - go mod download
  # Vet Go source code using the linter config (see .golang-ci.yml)
  - golangci-lint run
  - go test -v -mod=vendor ./...
  - go install -v -mod=vendor ./...
  - acmeshell -pebble -postAsGet -in docs/example.script.txt

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux

  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file: dist/acmeshell_*
    skip_cleanup: true
    overwrite: true
    file_glob: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
