language: go
go:
  - "1.11.x"
env:
  - GO111MODULE=on

# See: https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/
# We want to disable the install phase to rely on vendored deps
install: true

script:
  - go vet -v ./...
  - env GO11MODULE=on go test -v -mod=vendor ./...
  - env GO11MODULE=on go install -v -mod=vendor ./...
