baseURL = "http://www.acmeshell.com/"
languageCode = "en-us"
title = "ACME Shell"
theme = "github-project-landing-page"

[author]
    name = "Daniel McCarney"
    email = "daniel@binaryparadox.net"

[params]
    description = "An ACME developer's best friend"
    author_url = "https://binaryparadox.net"
    project_url = "https://github.com/cpu/acmeshell"
    github_user_name = "cpu"
    github_project_name = "acmeshell"
