name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15' ]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -mod=vendor -v ./...

    - name: Test
      run: go test -mod=vendor -v ./...
