name: Go
on:
  push:
  pull_request:
  schedule:
    # Run every 12 hours, at the 15 minute mark. E.g.
    # 2020-11-29 00:15:00 UTC, 2020-11-29 12:15:00 UTC, 2020-11-30 00:15:00 UTC
    - cron:  '15 */12 * * *'
jobs:

  build:
    name: Build and Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.15

    - name: Check out code
      uses: actions/checkout@v5

    - name: Check if modules are tidy
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
          echo "go.mod or go.sum are not tidy. Please run 'go mod tidy' locally and commit changes."
          git diff go.mod go.sum
          exit 1
        fi

    - name: Verify formatting
      # 'gofmt -l .' to list files whose formatting differs from gofmt's
      # 'test -z' to verify that the output is empty
      run: test -z "$(gofmt -l .)"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
